global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'vinhperfume215@gmail.com'
  smtp_auth_username: 'vinhperfume215@gmail.com'
  smtp_auth_password: 'exao rrsx rxsu hblj'
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 30s      
  group_interval: 5m    
  repeat_interval: 1h   

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'phamnguyentuanvinhh@gmail.com'
        send_resolved: true         