services:
  cleaningbiz-server:
    image: vinh2105/cleaningbiz-server:${SERVER_IMAGE_TAG}
    container_name: cleaningbiz-server-prod
    restart: always
    ports:
      - "127.0.0.1:4001:4001"
    env_file:
      - ../cleaningbiz-server/.env
    depends_on:
      - mongodb
    networks:
      - cleaningbiz-network

  cleaningbiz-client:
    image: vinh2105/cleaningbiz-client:${CLIENT_IMAGE_TAG}
    container_name: cleaningbiz-client-prod
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../cleaningbiz-client/.env
    depends_on:
      - cleaningbiz-server
    networks:
      - cleaningbiz-network

  mongodb:
    container_name: mongodb_container
    image: mongo:8.0.5
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: iamadmin2105
      MONGO_INITDB_DATABASE: cleaningbiz
    command:
      [
        "mongod",
        "-v",
        "--bind_ip",
        "0.0.0.0",
        "--logpath",
        "/var/log/mongodb/mongod.log",
        "--logRotate",
        "reopen",
        "--logappend",
      ]
    volumes:
      - ./docker-volumes/data:/data/db
      - ./cleaningbiz-init:/docker-entrypoint-initdb.d
      - ./docker-volumes/log:/var/log/mongodb
      - ./docker-volumes/logrotate/mongod.conf:/etc/logrotate.d/mongod.conf
    networks:
      - cleaningbiz-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - cleaningbiz-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert_rules.yaml:/etc/prometheus/alert_rules.yaml
    networks:
      - cleaningbiz-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - cleaningbiz-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    networks:
      - cleaningbiz-network

volumes:
  mongodb_data:

networks:
  cleaningbiz-network:
