services:
  cleaningbiz-server:
    image: vinh2105/cleaningbiz-server:${SERVER_IMAGE_TAG}
    container_name: cleaningbiz-server-prod
    restart: always
    ports:
      - "127.0.0.1:4001:4001"
    env_file:
      - ../cleaningbiz-server/.env
    depends_on:
      - mongodb
    networks:
      - cleaningbiz-network

  cleaningbiz-client:
    image: vinh2105/cleaningbiz-client:${CLIENT_IMAGE_TAG}
    container_name: cleaningbiz-client-prod
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../cleaningbiz-client/.env
    depends_on:
      - cleaningbiz-server
    networks:
      - cleaningbiz-network

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: iamadmin2105
      MONGO_INITDB_DATABASE: cleaningbiz
    volumes:
      - ./docker-volumes/data:/data/db
      - ./cleaningbiz-init:/docker-entrypoint-initdb.d
      - ./docker-volumes/log:/var/log/mongodb
    networks:
      - cleaningbiz-network

volumes:
  mongodb_data:

networks:
  cleaningbiz-network:
