services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: donothackmeagain
      MONGO_INITDB_DATABASE: cleaningbiz
    volumes:
      - ./docker-volumes/data:/data/db
      - ./cleaningbiz-init:/docker-entrypoint-initdb.d
volumes:
  mongodb_data:
