global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']
    scrape_interval: 15s
